// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryjczccmwjyseonjzesz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5amN6Y2Ntd2p5c2Vvbmp6ZXN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1OTc4OTQsImV4cCI6MjA1NDE3Mzg5NH0.8SSv6YKFSdPAObtigs87wuWPN2o5b-iMnW9jpbd3me0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);